version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    hostname: app
    networks:
      - node-network
    volumes:
      - ../:/usr/src/app
    tty: true
    depends_on:
      - db
    ports:
      - "3000:3000"

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ../mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

  nginx:
    build:
      context: ../nginx
      dockerfile: Dockerfile
    container_name: nginx
    hostname: nginx
    networks:
      - node-network
    ports:
      - "8080:80"
    depends_on:
      - app
      - db

networks:
  node-network:
    driver: bridge
  